apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample
  annotations:
    github.com/project-slug: test-automation-actions/karate-test-demo
spec:
  type: websites
  owner: CNCF
  lifecycle: production
