name: Export GitHub Secrets

on:
  workflow_dispatch:  # Manual trigger

permissions:
  actions: read  # Required to access secrets
  contents: read

jobs:
  export-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch and Save Secrets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          SECRETS_JSON: ${{ toJSON(secrets) }}
          VARS_JSON: ${{ toJSON(vars) }}
        run: |
          echo "Fetching secrets..."
          
          # Get Org Secrets
          echo '${SECRETS_JSON}' > secrets.json
          

      - name: Upload Secrets as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-secrets
          path: secrets.json
          retention-days: 7  # Store for 7 days
