name: Print Raw Multiline Input

on:
  workflow_dispatch:
    inputs:
      repo_tags:
        description: 'Enter each repo and tags in format repo:tag1,tag2 (one per line)'
        required: true
        default: "repo1:tag1,tag2 repo2:tag3,tag4 repo3:tagX"

jobs:
  print-input:
    runs-on: ubuntu-latest
    steps:
      - name: Print Raw Input Exactly As-Is
        run: |
          echo "Raw repo_tags input string:"
          echo "${{ github.event.inputs.repo_tags }}"
